import "./globals.css";
import { Inter } from "next/font/google";

import Navbar from "@/components/Navbar/Navbar";
import Header from "@/components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="grid grid-cols-12">
        <aside className="col-span-2 bg-gray-200">
          <Navbar />
        </aside>

        <main className="col-span-10">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
